### ISSUE TITLE
Can't see About page

### ISSUE THREAD

**Issue by drcrazy** [FallenWorlds/AddOnStudio#1]
Hello. 

I've checked on both AddOnStudioWoW-7.0.221018.0 and AddOnStudioWoW-7.0.220929.0 with VS 2022.

When I click on "Help -> About AddOn Studio for World of Warcraft" menu item it shows "Object reference not set to an instance of an object" dialog rather then information about AS. 

Menu item: 
![image](https://user-images.githubusercontent.com/1382352/197250075-888b337d-40d3-4d87-aa8f-c8b8eb922e1a.png)

Dialog:
![image](https://user-images.githubusercontent.com/1382352/197250121-0bb1c42a-b83c-44fa-be4c-4482a57d7a7c.png)

**Expected result**:
Proper dialog with AS version shown.

**Comment by drcrazy** [comment]
Issue reproducible if you start AS under unprivileged user account

**Comment by BearSleepy** [comment]
Fixed in AddOn Studio 221021.0
https://addonstudio.org/wow/2022/release

**Comment by drcrazy** [comment]
It works now

![image](https://user-images.githubusercontent.com/1382352/197307766-77b4ffa6-90b3-4bd8-989b-89b1181a429a.png)

**Comment by BearSleepy** [comment]
Sweet!
Thanks again for letting me know
